# Generated by Django 3.0.5 on 2020-12-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vol', '0002_volunteer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pandemic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('risk_level', models.CharField(max_length=100)),
                ('impact', models.CharField(max_length=100)),
            ],
        ),
    ]
