# Generated by Django 3.0.5 on 2020-12-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vol', '0005_auto_20201210_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='age',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
