# Generated by Django 3.0.5 on 2020-12-11 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vol', '0007_work_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='location',
        ),
        migrations.AddField(
            model_name='pandemic',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now=True)),
                ('member1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member1', to='vol.Volunteer')),
                ('member2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member2', to='vol.Volunteer')),
                ('member3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member3', to='vol.Volunteer')),
                ('member4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member4', to='vol.Volunteer')),
                ('member5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member5', to='vol.Volunteer')),
                ('pandemic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vol.Pandemic')),
            ],
        ),
    ]
