# Generated by Django 3.0.5 on 2020-12-13 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vol', '0008_auto_20201211_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.CharField(default='Started Working', max_length=100),
        ),
        migrations.CreateModel(
            name='WorkRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('confirm', 'confirm')], default='pending', max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('pandemic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vol.Pandemic')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vol.Volunteer')),
            ],
        ),
    ]
